
# loaded the data 
```{r}
data <- read.csv('data/healthcare-dataset-stroke-data.csv')
data
```

# Removing the missing values 
```{r}
# Checking if there is missing data in our data set
#data[data == ""]  # Printing the missing data
#data[data == ""] <- NA # replacing the missing data as NA
#head(data)
print("Structure of the data: ")

str(data) # Checking the structure of the dataframe
cat("\n")
# After seeing the data structure, BMI was in character data type so we convert it into numeric (Double)
data$bmi <- as.numeric(data$bmi)
print("###########################################################################################################################")
cat("\n")
print("Summary of the dataframe: ")
cat("\n")
summary(data)
```
# Replacing NA values in BMI with median

Why median ? 

Replacing missing values with the median because the distribution is left skewed.

```{r}

boxplot(data$bmi, horizontal=TRUE, pch=20, main="BMI")

hist(data$bmi)

```

```{r}
data$bmi <- ifelse(is.na(data$bmi), median(data$bmi, na.rm=TRUE), data$bmi)

# Checking the summary of the data again
print("Data Summary:")
summary(data)
cat("\n")
cat("\n")
print("Number of N/A data in our data:")
sum(is.na(data))

```
```{r}
# Calculate the lower and upper bounds for outliers
Q1 <- quantile(data$bmi, 0.25)
Q3 <- quantile(data$bmi, 0.75)
IQR <- Q3 - Q1
lower_bound <- Q1 - 1.5 * IQR
upper_bound <- Q3 + 1.5 * IQR

# Identify the outliers
outliers <- which(data$bmi < lower_bound | data$bmi > upper_bound)

# Replace outliers with the median value
median_val <- median(data$bmi)
data$bmi[outliers] <- median_val

boxplot(data$bmi, horizontal=TRUE, pch=20, main="BMI")

```



```{r}


boxplot(data$bmi, horizontal=TRUE, pch=20, main="BMI")

hist(data$bmi)

```


# BOX PLOT

```{r}
# the variables and plot parameters being defined
variables <- c("age", "avg_glucose_level", "bmi")
xlabels <- c("Stroke", "Stroke", "Stroke")
ylabels <- c("Age", "Average Glucose Level", "BMI")
titles <- c("Distribution of Age by Stroke", "Distribution of Average Glucose Level by Stroke", "Distribution of BMI by Stroke")
legend_loc <- c("bottom","topleft", "bottom")
colors <- c("yellow", "orange")

# for loop to plot the box plots
for (i in 1:length(variables)) {
  boxplot(formula(paste(variables[i], "~ stroke")), data = data,
          xlab = xlabels[i], ylab = ylabels[i], main = titles[i],
          horizontal = FALSE, col = colors)
  
  legend(legend_loc[i], legend = c("Stroke", "No stroke"), fill = colors)
}
```

# HISTOGRAM 
```{r}
# Titles and labels for histograms
titles <- c("Distribution of Age", "Distribution of Average Glucose Level", "Distribution of BMI")
xlabels <- c("Age", "Average Glucose Level", "BMI")

# Colors for histograms
colors_histogram <- c(10, 3, 5)

# Loop through the variables
for (i in 1:length(variables)) {
  # Plot histogram
  hist(data[[variables[i]]], xlab = xlabels[i], main = titles[i], col = colors_histogram[i])
}


```

# Barplot
```{r}
# Bar plot for Gender
bar_color <- c("pink","blue", "purple")
barplot(table(data$gender), xlab = "Gender", ylab = "Count", main = "Distribution of Gender", col= bar_color)
```
```{r}
bar_color <- c("indianred","lightgreen")
barplot(table(data$ever_married), xlab = "Ever married", ylab = "Count", main = "Distribution of Maried Status", col= bar_color)
```
```{r}
bar_color <- c("lightcoral","lightsalmon","grey", "lightskyblue","mediumaquamarine")
barplot(table(data$work_type), xlab = "Work Type", ylab = "Count", main = "Distribution of Work Type", col= bar_color)
```

```{r}
bar_color <- c("papayawhip","orchid")
barplot(table(data$Residence_type), xlab = "Resident Type", ylab = "Count", main = "Distribution of Resident Type", col= bar_color)
```

```{r}
bar_color <- c("turquoise","wheat","tomato","thistle")
barplot(table(data$smoking_status), xlab = "Smoking Status", ylab = "Count", main = "Distribution of Smoking Status", col= bar_color)
```

